export interface optionsInter {
    val: any;
    length: number;
}
export interface appointLen {
    start: number;
    end: number;
    val: any;
}
export declare type interCheck = (val: any) => boolean;
export declare type superInterCheck = (options: optionsInter) => boolean;
export declare type appointLenInterCheck = (options: appointLen) => boolean;
export declare const checkPhone: interCheck;
export declare const checkEmail: interCheck;
export declare const checkUrl: interCheck;
export declare const checkDomesticTelephone: interCheck;
export declare const checkNotSpecial: appointLenInterCheck;
export declare const checkHtml: interCheck;
export declare const checkQQ: interCheck;
export declare const checkPostOffice: interCheck;
export declare const checkIP: interCheck;
export declare const checkDateFormat: interCheck;
export declare const checkLowerCase: interCheck;
export declare const checkUpperCase: interCheck;
export declare const checkAlphabets: interCheck;
export declare const checkCID: interCheck;
export declare const checkPasswordSpecification: appointLenInterCheck;
export declare const checkDChineseCharacterDetection: interCheck;
export declare const checkNumberUnderscoreletter: interCheck;
export declare const checkChineseNumberEnglishUnderline: interCheck;
export declare const checkSpecialCharacters: interCheck;
export declare const checkStrComposedOfNumber: interCheck;
export declare const checkNumberLength: superInterCheck;
export declare const checkAppointLen: appointLenInterCheck;
export declare const checkZeroAndNonZero: interCheck;
export declare const checkTwoDecimalplaces: interCheck;
export declare const checkDecimalplaces: interCheck;
export declare const checkPND: interCheck;
export declare const checkPositiveTDP: interCheck;
export declare const checkOandTPositive: interCheck;
export declare const checkNonzeroPositive: interCheck;
export declare const checkNonzeroNegative: interCheck;
export declare const checkNotNegative: interCheck;
export declare const checkNotPositive: interCheck;
export declare const checkNotNegativeFloat: interCheck;
export declare const checkNotPositiveFloat: interCheck;
export declare const checkPositiveFloat: interCheck;
export declare const checkNegativeFloat: interCheck;
export declare const checkFloat: interCheck;
declare const _default: {
    checkPhone: interCheck;
    checkEmail: interCheck;
    checkUrl: interCheck;
    checkDomesticTelephone: interCheck;
    checkNotSpecial: appointLenInterCheck;
    checkHtml: interCheck;
    checkQQ: interCheck;
    checkPostOffice: interCheck;
    checkDateFormat: interCheck;
    checkLowerCase: interCheck;
    checkUpperCase: interCheck;
    checkAlphabets: interCheck;
    checkCID: interCheck;
    checkIP: interCheck;
    checkPasswordSpecification: appointLenInterCheck;
    checkDChineseCharacterDetection: interCheck;
    checkNumberUnderscoreletter: interCheck;
    checkChineseNumberEnglishUnderline: interCheck;
    checkSpecialCharacters: interCheck;
    checkStrComposedOfNumber: interCheck;
    checkNumberLength: superInterCheck;
    checkAppointLen: appointLenInterCheck;
    checkZeroAndNonZero: interCheck;
    checkTwoDecimalplaces: interCheck;
    checkDecimalplaces: interCheck;
    checkPND: interCheck;
    checkPositiveTDP: interCheck;
    checkOandTPositive: interCheck;
    checkNonzeroPositive: interCheck;
    checkNonzeroNegative: interCheck;
    checkNotNegative: interCheck;
    checkNotPositive: interCheck;
    checkNotNegativeFloat: interCheck;
    checkNotPositiveFloat: interCheck;
    checkPositiveFloat: interCheck;
    checkNegativeFloat: interCheck;
    checkFloat: interCheck;
};
export default _default;
