import { throttle, debounce, delay, getUrlKey, getRawType, cached, capitalize, isStatic, unique, tasInterface } from './packages/utils';
import { getCooick, setCooick, removeCooick } from './packages/cooick';
import { setLocalStorage, getLocalStorage, removeLocalStorage } from './packages/localStorage';
import { typeOf } from './packages/typeOf';
import { clipboard } from './packages/clipboard';
import { decopy } from './packages/decopy';
import { checkAlphabets, checkAppointLen, checkCID, checkChineseNumberEnglishUnderline, checkDChineseCharacterDetection, checkDateFormat, checkDecimalplaces, checkDomesticTelephone, checkEmail, checkFloat, checkHtml, checkIP, checkLowerCase, checkNegativeFloat, checkNonzeroNegative, checkNonzeroPositive, checkNotNegative, checkNotNegativeFloat, checkNotPositive, checkNotPositiveFloat, checkNotSpecial, checkNumberLength, checkNumberUnderscoreletter, checkOandTPositive, checkPND, checkPasswordSpecification, checkPhone, checkPositiveFloat, checkPositiveTDP, checkPostOffice, checkQQ, checkSpecialCharacters, checkStrComposedOfNumber, checkTwoDecimalplaces, checkUpperCase, checkUrl, checkZeroAndNonZero, interCheck, superInterCheck, appointLenInterCheck, appointLen, optionsInter } from './packages/regExp';
import { getAfterCountDays, getFirstDayOfSeason, getHoroscope, getTime, getLastDayOfMonth, getWeek, getYearDay, getYearWeek, dateDifference, dateFormat, remainderTime, TimeOptionsFunc, dateType, TimeFormal } from './packages/date';
export { decopy, throttle, debounce, delay, getUrlKey, getRawType, cached, capitalize, isStatic, unique, tasInterface, getCooick, setCooick, removeCooick, setLocalStorage, getLocalStorage, removeLocalStorage, typeOf, clipboard, checkAlphabets, checkAppointLen, checkCID, checkChineseNumberEnglishUnderline, checkDChineseCharacterDetection, checkDateFormat, checkDecimalplaces, checkDomesticTelephone, checkEmail, checkFloat, checkHtml, checkIP, checkLowerCase, checkNegativeFloat, checkNonzeroNegative, checkNonzeroPositive, checkNotNegative, checkNotNegativeFloat, checkNotPositive, checkNotPositiveFloat, checkNotSpecial, checkNumberLength, checkNumberUnderscoreletter, checkOandTPositive, checkPND, checkPasswordSpecification, checkPhone, checkPositiveFloat, checkPositiveTDP, checkPostOffice, checkQQ, checkSpecialCharacters, checkStrComposedOfNumber, checkTwoDecimalplaces, checkUpperCase, checkUrl, checkZeroAndNonZero, getAfterCountDays, getFirstDayOfSeason, getHoroscope, getTime, getLastDayOfMonth, getWeek, getYearDay, getYearWeek, dateDifference, dateFormat, remainderTime, TimeOptionsFunc, dateType, TimeFormal, interCheck, superInterCheck, appointLenInterCheck, appointLen, optionsInter };
